Document: atomicles
Title: Debian atomicles Manual
Author: <insert document author here>
Abstract: This manual describes what atomicles is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/atomicles/atomicles.sgml.gz

Format: postscript
Files: /usr/share/doc/atomicles/atomicles.ps.gz

Format: text
Files: /usr/share/doc/atomicles/atomicles.text.gz

Format: HTML
Index: /usr/share/doc/atomicles/html/index.html
Files: /usr/share/doc/atomicles/html/*.html
